# Generated by Django 5.0.4 on 2024-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
