# Generated by Django 5.0.4 on 2024-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='two_fa_method',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=10),
        ),
    ]
