# Generated by Django 5.0.4 on 2024-05-06 16:18

from django.db import migrations
def create_missing_profiles_and_tokens(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Player = apps.get_model('myapp', 'Player')
    Token = apps.get_model('authtoken', 'Token')

    for user in User.objects.all():
        Player.objects.get_or_create(user=user)
        Token.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_player_display_name_player_friends_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'), 
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.RunPython(create_missing_profiles_and_tokens, reverse_code=migrations.RunPython.noop),

    ]
