# Generated by Django 5.0.4 on 2024-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_player_two_fa_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='details',
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='online_status',
            field=models.IntegerField(default=0),
        ),
    ]
