# Generated by Django 5.0.4 on 2024-05-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_match_details_match_opponent_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
