# Generated by Django 5.0.6 on 2024-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_player_otp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(null=True)),
                ('player2', models.CharField(null=True)),
                ('winner', models.CharField(null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('played_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
