# Generated by Django 5.0.6 on 2024-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_mymatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='otp_enabled',
            new_name='two_fa_activated',
        ),
        migrations.AddField(
            model_name='player',
            name='two_fa_requested',
            field=models.BooleanField(default=False),
        ),
    ]
